name: "kyrremann"
description: "My personal site, where you find the most up to date infor about me!"
author: "Kyrre Havik Erksen"
url: "http://kyrremann.github.io"

author-bio: "Something, something about Kyrremann. I'm a developer in Norway. Want to make games, end up playing games."

markdown: kramdown
permalink: pretty
sass:
  sass_dir: _scss
  style: :compressed
